name: Run

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker container
        run: |
          docker pull thecatvoid/gentoo:latest
          docker build . -t thecatvoid/gentoo:latest
          docker run -it -d --name gentoo_container gentoo:latest bash

      - name: Start
        run: |
          id="$(docker ps --filter "name=gentoo_container" --format "{{.ID}}")"
          docker_root="$(docker inspect --format="{{.GraphDriver.Data.MergedDir}}" $id)"
          sudo cp -af ./* $docker_root/
          echo "GIT_TOKEN=${{ secrets.GIT_TOKEN }}" >> $docker_root/etc/environment 
          sudo docker exec gentoo /gentoo.sh setup_build

